version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
          context: .
          dockerfile: Dockerfile
        image: php:7-alpine
        working_dir: /var/www
        networks:
          - back
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        links:
          - redis
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    redis:
      networks:
        - back
      image: redis
      restart: always
      volumes:
        - ./storage/redis/data:/data

networks:
  back:
    driver: bridge
